name: BuildWebview
on:
  push:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev xvfb -y
      - name: Build and run tests
        run: xvfb-run ./script/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "webview-linux64"
          path: ./build

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and run tests
        run: ./script/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "webview-mac64"
          path: ./build

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and run tests
        run: ./script/build.bat
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "webview-win64"
          path: ./build
